# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Guidomia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Guidomia
  
  pod 'SnapKit', '~> 5.0.1' # Programmatic Auto Layout
  pod 'SwiftFormat/CLI', '~> 0.49.2' # Code Formatter

  target 'GuidomiaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GuidomiaUITests' do
    # Pods for testing
  end

end

# Post Install
post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
		end
	end
end
